### ISSUE TITLE
Clean build

### ISSUE THREAD

**Issue by binkley** [klogging/slf4j-klogging#1]
A new contributor should be able to fork the repo, clone locally, and run `./gradlew build` successfully out of the box

**Comment by binkley** [comment]
@mjstrasser Does `./gradlew clean build` work for you?

I'm going to experiment with a Docker image, and see what happens.

**Comment by mjstrasser** [comment]
Did you try using `./batect build`?

**Comment by binkley** [comment]
This needs verification (and possible fixing) by a new contributor who starts from a clean, freshly cloned repo.

**Comment by mjstrasser** [comment]
Checked today: builds OK.

**Comment by binkley** [comment]
I checked today, and it fails:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessKotlin'.
> Error on line: 1, column: 1
  rule: max-line-length
  Exceeded max line length (80)

**Comment by mjstrasser** [comment]
Try again @binkley 
Max line lengths are now set explicitly for the project.

**Comment by binkley** [comment]
@mjstrasser Thanks -- build is fully green.

FYI -- I appreciate the 80 character line limit. This is my choice as well in my projects.
