### ISSUE TITLE
Support for SLF4J 2.0

### ISSUE THREAD

**Issue by skotsj** [klogging/slf4j-klogging#29]
Binding doesn't work with slf4j 2.0 which is now default in Spring.

https://www.slf4j.org/faq.html#changesInVersion200 
https://www.slf4j.org/codes.html#ignoredBindings

**Comment by mjstrasser** [comment]
@skotsj Thanks for bringing this to my attention. I am transferring it to slf4j-klogging repo, where I will address it.

**Comment by mjstrasser** [comment]
@skotsj I have updated `slf4j-klogging` and `klogging-spring-boot-starter` to work with SLF4J 2.x and Spring Boot 3.x.

Please try version 0.3.0 of either and let me know if it works for you (they both work in my testing).

**Comment by skotsj** [comment]
Seems to work well, thanks

**Comment by mjstrasser** [comment]
Good to know!
